name: Build and Release pack/unpack executables

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pkg
        run: npm install -g pkg

      - name: Build executables
        run: |
          TARGET=$([ "${{ matrix.os }}" = "windows-latest" ] && echo "win" || ([ "${{ matrix.os }}" = "macos-latest" ] && echo "macos" || echo "linux"))
          OUT1="pack$([ "$TARGET" = "win" ] && echo '.exe' || echo '')"
          OUT2="unpack$([ "$TARGET" = "win" ] && echo '.exe' || echo '')"
          pkg pack.js --targets node18-$TARGET --output "$OUT1"
          pkg unpack.js --targets node18-$TARGET --output "$OUT2"

      - name: Collect artifacts
        run: |
          mkdir dist
          cp pack* dist/
          cp unpack* dist/
          ls -lh dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create or Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: "Nightly Build"
          draft: false
          prerelease: true
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
